### ISSUE TITLE
"Lock-On" weapons do not display in printout

### ISSUE THREAD

**Issue by dukea42** [erkannt/text2tabletop#1]
The hyphen "-" in Lock-On seems to prevent the related weapon from being displayed.

Sample case of Missile Pod on SSH Gator:

```
Gator [1] Q4+ D3+ | 70pts | Fearless, Predator, Tough(3)
Bash (A2), Bludgeon (A1, Impact(1)), Missile Pod (18", A1, AP(2), Lock-On), Power Claw (A1, AP(1), Rending)
```

**Comment by erkannt** [comment]
Thanks for raising this! Should be fixed once the latest commit gets deployed. Let me know if you find anything else.
