### ISSUE TITLE
Heroes joined to units break parsing

### ISSUE THREAD

**Issue by Andyrgreig** [erkannt/text2tabletop#2]
Pasting an army from Army Forge which contains a hero joined to a unit causes errors for all units after the hero in the text block. Attached are screenshots showing the output for 2 army lists. The lists are identical, except that in one the hero is attached to a unit and in the other it is unattached. Below are links to army lists I used.

https://army-forge.onepagerules.com/share?id=r3TFYI0ImFpY&name=Vampiric_Undead
https://army-forge.onepagerules.com/share?id=r3TFYI0ImFpY&name=Vampiric_Undead%20-%20Copy

![1](https://github.com/erkannt/text2tabletop/assets/37780199/61ca1ff6-6b03-4a4a-9911-37af33da3fb2)
![2](https://github.com/erkannt/text2tabletop/assets/37780199/ffde30e7-dc55-4fe1-b265-f2da0bf51a1a)

**Comment by erkannt** [comment]
:rocket: Fixed
